# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_port', models.SmallIntegerField(verbose_name='数据库端口')),
                ('db_name', models.CharField(max_length=64, verbose_name='数据库名称')),
                ('db_user', models.CharField(max_length=64, verbose_name='数据库账号')),
                ('db_password', models.CharField(max_length=64, verbose_name='数据库密码')),
                ('db_memo', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据库配置表',
                'verbose_name_plural': '数据库配置表',
                'db_table': 'ops_db_config',
            },
        ),
        migrations.CreateModel(
            name='DBLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_sql_content', models.TextField(verbose_name='SQL内容')),
                ('db_sql_res', models.TextField(verbose_name='执行结果')),
                ('db_sql_res_thead', models.CharField(blank=True, default='', max_length=256, verbose_name='查询结果的表头')),
                ('db_run_datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('db_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanager.DBConfig', verbose_name='登录数据库')),
            ],
            options={
                'verbose_name': '数据库操作记录表',
                'verbose_name_plural': '数据库操作记录表',
                'db_table': 'ops_db_log',
            },
        ),
    ]
