# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbmanager', '0001_initial'),
        ('projs', '0002_auto_20191121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='dblog',
            name='db_login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行用户'),
        ),
        migrations.AddField(
            model_name='dbconfig',
            name='db_group',
            field=models.ManyToManyField(to='auth.Group', verbose_name='使用组'),
        ),
        migrations.AddField(
            model_name='dbconfig',
            name='db_server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projs.Service', verbose_name='数据库服务器'),
        ),
        migrations.AlterUniqueTogether(
            name='dbconfig',
            unique_together={('db_server', 'db_name', 'db_port')},
        ),
    ]
