# Generated by Django 2.0.12 on 2020-01-09 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_dep', to='users.Department', verbose_name='所属部门'),
        ),
    ]
