# Generated by Django 2.0.5 on 2019-12-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_cnname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leader_str',
            field=models.SmallIntegerField(choices=[(1, '普通员工'), (0, '部门负责人')], default=1, verbose_name='员工级别'),
        ),
    ]
