# Generated by Django 2.0.12 on 2020-01-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200109_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='department',
            new_name='department_id',
        ),
    ]
