# Generated by Django 2.0.5 on 2019-12-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_leader_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('enname', models.CharField(max_length=32, verbose_name='部门英文名称')),
                ('parent', models.SmallIntegerField(default=0, verbose_name='是否是顶级部门')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_dep', to='users.Department', verbose_name='所属部门'),
            preserve_default=False,
        ),
    ]
