# Generated by Django 2.0.5 on 2019-12-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191229_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department_id',
        ),
    ]
