# Generated by Django 2.0.5 on 2019-12-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='enname',
            field=models.CharField(max_length=32, unique=True, verbose_name='部门英文名称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='部门名称'),
        ),
    ]
