# Generated by Django 2.0.5 on 2019-12-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191229_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='mtime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改时间'),
        ),
    ]
