# Generated by Django 2.0.5 on 2019-12-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191229_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='leader_str',
            new_name='leader',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_id',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_dep', to='users.Department', verbose_name='所属部门'),
            preserve_default=False,
        ),
    ]
