# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='文章标题')),
                ('html_content', models.TextField(verbose_name='HTML内容')),
                ('md_content', models.TextField(verbose_name='markdown内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': 'wiki文章',
                'verbose_name_plural': 'wiki文章',
                'db_table': 'ops_wiki_post',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wiki/images/%Y/%m/%d/', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': 'wiki文章图片',
                'verbose_name_plural': 'wiki文章图片',
                'db_table': 'ops_wiki_upload_image',
            },
        ),
        migrations.CreateModel(
            name='WikiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_file', models.FileField(unique=True, upload_to='wiki/upload/%Y/%m/%d/')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传人员')),
            ],
            options={
                'verbose_name': 'wiki共享文件',
                'verbose_name_plural': 'wiki共享文件',
                'db_table': 'ops_wiki_file',
            },
        ),
    ]
