# Generated by Django 2.0.12 on 2020-01-09 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_server', models.CharField(max_length=32, verbose_name='登录主机')),
                ('admin_remote_ip', models.GenericIPAddressField(verbose_name='远程地址')),
                ('admin_start_time', models.CharField(max_length=64, verbose_name='开始时间')),
                ('admin_login_status_time', models.CharField(max_length=16, verbose_name='登录时长')),
                ('admin_record_file', models.CharField(max_length=256, verbose_name='操作记录')),
                ('admin_record_mode', models.CharField(choices=[('ssh', 'ssh'), ('guacamole', 'guacamole')], default='ssh', max_length=10, verbose_name='登录协议')),
                ('admin_login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录管理用户记录表',
                'verbose_name_plural': '登录管理用户记录表',
                'db_table': 'ops_admin_record',
            },
        ),
        migrations.CreateModel(
            name='AssetProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_provider_name', models.CharField(max_length=64, unique=True, verbose_name='供应商名称')),
                ('asset_provider_contact', models.CharField(blank=True, max_length=32, null=True, verbose_name='技术支持人员')),
                ('asset_provider_telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='支持电话')),
                ('asset_provider_memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商表',
                'verbose_name_plural': '供应商表',
                'db_table': 'ops_asset_provider',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('network', '网络设备'), ('office', '办公设备'), ('security', '安全设备'), ('storage', '存储设备'), ('software', '软件资产')], default='server', max_length=100, verbose_name='资产类型')),
                ('asset_nu', models.CharField(max_length=100, unique=True, verbose_name='资产编号')),
                ('asset_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产型号')),
                ('asset_status', models.SmallIntegerField(choices=[(0, '已上线'), (1, '已下线'), (2, '维修中'), (3, '已入库'), (4, '未使用')], default=0, verbose_name='状态')),
                ('asset_management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('asset_system_type', models.SmallIntegerField(blank=True, null=True, verbose_name='操作系统类型')),
                ('asset_hostname', models.CharField(blank=True, max_length=30, null=True, verbose_name='主机名称')),
                ('asset_purchase_day', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('asset_expire_day', models.DateField(blank=True, null=True, verbose_name='过保日期')),
                ('asset_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='价格(万元)')),
                ('asset_create_time', models.DateTimeField(auto_now_add=True)),
                ('asset_update_time', models.DateTimeField(auto_now_add=True)),
                ('asset_memo', models.TextField(blank=True, help_text='配置说明或一些注意事项', null=True, verbose_name='备注')),
                ('asset_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员')),
            ],
            options={
                'verbose_name': '总资产表',
                'verbose_name_plural': '总资产表',
                'db_table': 'ops_assets',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(max_length=64, unique=True, verbose_name='机柜名称')),
                ('cabinet_memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机柜表',
                'verbose_name_plural': '机柜表',
                'db_table': 'ops_cabinet',
            },
        ),
        migrations.CreateModel(
            name='DiskAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘容量')),
                ('disk_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘状态')),
                ('disk_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘型号')),
                ('disk_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘生产商')),
                ('disk_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘序列号')),
                ('disk_slot', models.SmallIntegerField(blank=True, null=True, verbose_name='硬盘插槽')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_assets', to='assets.Assets')),
            ],
            options={
                'verbose_name': '磁盘资产表',
                'verbose_name_plural': '磁盘资产表',
                'db_table': 'ops_disk_assets',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=64, unique=True, verbose_name='机房名称')),
                ('idc_address', models.CharField(max_length=100, unique=True, verbose_name='机房地址')),
                ('idc_contact', models.CharField(max_length=32, verbose_name='机房联系人')),
                ('idc_telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='支持电话')),
                ('idc_memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机房表',
                'verbose_name_plural': '机房表',
                'db_table': 'ops_idc',
            },
        ),
        migrations.CreateModel(
            name='NetworkAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_type', models.SmallIntegerField(choices=[(0, '路由器'), (1, '交换机'), (2, '负载均衡'), (3, 'wifi'), (4, 'VPN'), (5, '其它')], default=0, verbose_name='网络设备类型')),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
            ],
            options={
                'verbose_name': '网络资产表',
                'verbose_name_plural': '网络资产表',
                'db_table': 'ops_network_assets',
            },
        ),
        migrations.CreateModel(
            name='NetworkCardAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_card_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='网卡名称')),
                ('network_card_mac', models.CharField(blank=True, max_length=64, null=True, verbose_name='MAC地址')),
                ('network_card_ip', models.CharField(blank=True, max_length=16, null=True, verbose_name='IP地址')),
                ('network_card_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='网卡类型')),
                ('network_card_mtu', models.CharField(blank=True, max_length=50, null=True, verbose_name='MTU')),
                ('network_card_status', models.SmallIntegerField(blank=True, null=True, verbose_name='网卡状态')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_card_assets', to='assets.Assets')),
            ],
            options={
                'verbose_name': '服务器网卡资产表',
                'verbose_name_plural': '服务器网卡资产表',
                'db_table': 'ops_network_card_assets',
            },
        ),
        migrations.CreateModel(
            name='OfficeAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.SmallIntegerField(choices=[(0, 'PC机'), (1, '打印机'), (2, '扫描仪'), (3, '其它')], default=0, verbose_name='办公设备类型')),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
            ],
            options={
                'verbose_name': '办公资产表',
                'verbose_name_plural': '办公资产表',
                'db_table': 'ops_office_assets',
            },
        ),
        migrations.CreateModel(
            name='PlatformName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=64, unique=True, verbose_name='平台名称')),
                ('platform_memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '平台表',
                'verbose_name_plural': '平台表',
                'db_table': 'ops_platform',
            },
        ),
        migrations.CreateModel(
            name='ProjectApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projapp_name', models.CharField(max_length=64, verbose_name='应用名称')),
                ('projapp_memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目应用表',
                'verbose_name_plural': '项目应用表',
                'db_table': 'ops_project_app',
            },
        ),
        migrations.CreateModel(
            name='ProjectEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projenv_name', models.CharField(max_length=64, unique=True, verbose_name='环境名称')),
                ('projenv_memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目环境表',
                'verbose_name_plural': '项目环境表',
                'db_table': 'ops_project_env',
            },
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projname_name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('projname_org', models.TextField(blank=True, default='', verbose_name='项目架构JSON数据')),
                ('projname_memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('platformname', models.ManyToManyField(blank=True, related_name='projectname', to='assets.PlatformName', verbose_name='所属平台')),
            ],
            options={
                'verbose_name': '项目名称表',
                'verbose_name_plural': '项目名称表',
                'db_table': 'ops_project_name',
            },
        ),
        migrations.CreateModel(
            name='RamAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='内存序列号')),
                ('ram_volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='内存容量')),
                ('ram_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='内存生产商')),
                ('ram_slot', models.SmallIntegerField(blank=True, null=True, verbose_name='内存插槽')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_assets', to='assets.Assets')),
            ],
            options={
                'verbose_name': '内存资产表',
                'verbose_name_plural': '内存资产表',
                'db_table': 'ops_ram_assets',
            },
        ),
        migrations.CreateModel(
            name='SecurityAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.SmallIntegerField(choices=[(0, '防火墙'), (1, '网关'), (2, '其它')], default=0, verbose_name='安全设备类型')),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
            ],
            options={
                'verbose_name': '安全资产表',
                'verbose_name_plural': '安全资产表',
                'db_table': 'ops_security_assets',
            },
        ),
        migrations.CreateModel(
            name='ServerAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.SmallIntegerField(choices=[(0, '物理机'), (1, '虚拟机'), (2, '云主机')], default=0, verbose_name='服务器类型')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='管理用户')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户密码')),
                ('port', models.DecimalField(blank=True, decimal_places=0, default=22, max_digits=6, null=True, verbose_name='SSH端口')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名称')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU型号')),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='物理CPU个数')),
                ('vcpu_number', models.SmallIntegerField(blank=True, null=True, verbose_name='逻辑CPU个数')),
                ('disk_total', models.CharField(blank=True, max_length=16, null=True, verbose_name='磁盘空间')),
                ('ram_total', models.SmallIntegerField(blank=True, null=True, verbose_name='内存容量')),
                ('kernel', models.CharField(blank=True, max_length=100, null=True, verbose_name='内核版本')),
                ('system', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作系统')),
                ('host_vars', models.TextField(blank=True, null=True, verbose_name='主机变量')),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
                ('hosted_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosted_on_server', to='assets.ServerAssets', verbose_name='宿主机')),
            ],
            options={
                'verbose_name': '服务器资产表',
                'verbose_name_plural': '服务器资产表',
                'db_table': 'ops_server_assets',
            },
        ),
        migrations.CreateModel(
            name='SoftwareAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_type', models.SmallIntegerField(choices=[(0, '操作系统'), (1, '办公/开发软件'), (2, '业务软件'), (3, '其它')], default=0, verbose_name='软件类型')),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
            ],
            options={
                'verbose_name': '软件资产表',
                'verbose_name_plural': '软件资产表',
                'db_table': 'ops_software_assets',
            },
        ),
        migrations.CreateModel(
            name='StorageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.SmallIntegerField(choices=[(0, '磁盘阵列'), (1, '网络存储器'), (2, '磁带库'), (3, '磁带机'), (4, '其它')], default=0, verbose_name='存储设备类型')),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
            ],
            options={
                'verbose_name': '存储资产表',
                'verbose_name_plural': '存储资产表',
                'db_table': 'ops_storage_assets',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=32, verbose_name='网站名称')),
                ('web_address', models.URLField(verbose_name='网站地址')),
                ('web_des', models.CharField(max_length=32, verbose_name='网站描述')),
            ],
            options={
                'verbose_name': '常用网站表',
                'verbose_name_plural': '常用网站表',
                'db_table': 'ops_website',
            },
        ),
        migrations.CreateModel(
            name='ZabbixAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_num', models.SmallIntegerField(verbose_name='告警数量')),
                ('alert_date', models.DateField(auto_now_add=True, verbose_name='告警日期')),
            ],
            options={
                'verbose_name': '告警记录表',
                'verbose_name_plural': '告警记录表',
                'db_table': 'ops_zabbix_alert',
            },
        ),
        migrations.AddField(
            model_name='projectapp',
            name='projectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectapp', to='assets.ProjectName'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='assets.IDC'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.Cabinet', verbose_name='所在机柜'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.PlatformName', verbose_name='所属平台'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.ProjectName', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_projapp',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.ProjectApp', verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_projenv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.ProjectEnv', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.AssetProvider', verbose_name='供应商'),
        ),
        migrations.AlterUniqueTogether(
            name='ramassets',
            unique_together={('asset', 'ram_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='projectapp',
            unique_together={('projectname', 'projapp_name')},
        ),
        migrations.AlterUniqueTogether(
            name='networkcardassets',
            unique_together={('asset', 'network_card_mac')},
        ),
        migrations.AlterUniqueTogether(
            name='diskassets',
            unique_together={('asset', 'disk_slot')},
        ),
    ]
