# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.Cabinet', verbose_name='所在机柜'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.PlatformName', verbose_name='所属平台'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.ProjectName', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_projapp',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.ProjectApp', verbose_name='所属应用'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_projenv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.ProjectEnv', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.AssetProvider', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='adminrecord',
            name='admin_login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='ramassets',
            unique_together={('asset', 'ram_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='projectapp',
            unique_together={('projectname', 'projapp_name')},
        ),
        migrations.AlterUniqueTogether(
            name='networkcardassets',
            unique_together={('asset', 'network_card_mac')},
        ),
        migrations.AlterUniqueTogether(
            name='diskassets',
            unique_together={('asset', 'disk_slot')},
        ),
    ]
