# Generated by Django 2.0.5 on 2019-12-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_hostname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='主机名称'),
        ),
    ]
