# Generated by Django 2.0.5 on 2019-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assets_asset_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_status',
            field=models.SmallIntegerField(choices=[(0, '已上线'), (1, '已下线'), (2, '维修中'), (3, '已入库'), (4, '未使用')], default=0, verbose_name='状态'),
        ),
    ]
