# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortBlackCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_commands', models.TextField(default='/bin/rm, /sbin/reboot, /sbin/halt, /sbin/shutdown, /usr/bin/passwd, /bin/su, /sbin/init, /bin/chmod, /bin/chown, /usr/sbin/visudo', verbose_name='默认禁用命令清单')),
            ],
            options={
                'verbose_name': '禁用命令清单表',
                'verbose_name_plural': '禁用命令清单表',
                'db_table': 'ops_fort_black_command',
            },
        ),
        migrations.CreateModel(
            name='FortRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fort', models.CharField(max_length=32, verbose_name='登录主机及用户')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='远程地址')),
                ('start_time', models.CharField(max_length=64, verbose_name='开始时间')),
                ('login_status_time', models.CharField(max_length=16, verbose_name='登录时长')),
                ('record_file', models.CharField(max_length=256, verbose_name='操作记录')),
                ('record_mode', models.CharField(choices=[('ssh', 'ssh'), ('guacamole', 'guacamole')], default='ssh', max_length=10, verbose_name='登录协议')),
            ],
            options={
                'verbose_name': '操作记录表',
                'verbose_name_plural': '操作记录表',
                'db_table': 'ops_fort_record',
            },
        ),
        migrations.CreateModel(
            name='FortServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_protocol', models.CharField(choices=[('ssh', 'ssh'), ('vnc', 'vnc'), ('rdp', 'rdp')], default='ssh', max_length=3, verbose_name='连接协议')),
                ('server_status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='是否允许web登录')),
            ],
            options={
                'verbose_name': '堡垒机表',
                'verbose_name_plural': '堡垒机表',
                'db_table': 'ops_fort_server',
                'permissions': (('view_fortserver', '读取堡垒机权限'), ('ssh_fortserver', '连接主机权限')),
            },
        ),
        migrations.CreateModel(
            name='FortServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fort_username', models.CharField(max_length=64, verbose_name='登录用户')),
                ('fort_password', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录密码')),
                ('fort_user_status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='用户状态')),
                ('fort_vnc_port', models.CharField(blank=True, default='', max_length=5, verbose_name='VNC连接端口')),
                ('fort_black_commands', models.TextField(blank=True, null=True, verbose_name='禁用命令清单')),
                ('fort_user_memo', models.TextField(blank=True, null=True, verbose_name='用户说明')),
                ('fort_belong_group', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='所属组')),
            ],
            options={
                'verbose_name': '堡垒机用户表',
                'verbose_name_plural': '堡垒机用户表',
                'db_table': 'ops_fort_user',
            },
        ),
    ]
