# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fort', '0001_initial'),
        ('assets', '0002_auto_20191121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortserveruser',
            name='fort_belong_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='fortserveruser',
            name='fort_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fort.FortServer'),
        ),
        migrations.AddField(
            model_name='fortserver',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.ServerAssets'),
        ),
        migrations.AddField(
            model_name='fortrecord',
            name='login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='fortserveruser',
            unique_together={('fort_server', 'fort_username')},
        ),
    ]
