# Generated by Django 2.0.12 on 2020-01-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confd_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confd_ns', models.CharField(max_length=40, verbose_name='命名空间')),
                ('confd_key', models.CharField(max_length=40, verbose_name='键')),
                ('confd_value', models.CharField(max_length=40, verbose_name='值')),
                ('confd_memo', models.CharField(blank=True, max_length=40, verbose_name='备注')),
                ('confd_deploy_status', models.IntegerField(choices=[(0, '已发布|正常'), (1, '未发布|新'), (2, '无|改'), (3, '无|删')], default=1, verbose_name='发布状态')),
                ('confd_status', models.IntegerField(choices=[(0, '已发布|正常'), (1, '未发布|新'), (2, '无|改'), (3, '无|删')], default=1, verbose_name='key状态')),
                ('confd_modified_user', models.CharField(max_length=40, verbose_name='最后修改用户')),
                ('confd_modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '配置明细',
                'verbose_name_plural': '配置明细',
                'db_table': 'ops_confd_detail',
                'permissions': (('confd_detail', '读取confd_detail列表权限'),),
            },
        ),
        migrations.CreateModel(
            name='Config_Confd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confd_name', models.CharField(max_length=40, verbose_name='配置名称')),
                ('confd_ns', models.CharField(max_length=40, verbose_name='命名空间')),
                ('confd_memo', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('asset_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confd_platform', to='assets.PlatformName', verbose_name='平台')),
                ('asset_proj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.ProjectName', verbose_name='项目')),
                ('asset_projapp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.ProjectApp', verbose_name='应用')),
                ('asset_projenv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.ProjectEnv', verbose_name='环境')),
            ],
            options={
                'verbose_name': '配置表',
                'verbose_name_plural': '配置表',
                'db_table': 'ops_config_confd',
                'permissions': (('confd_projs', '读取confd_projs列表权限'),),
            },
        ),
        migrations.AddField(
            model_name='confd_detail',
            name='confd_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confd.Config_Confd', verbose_name='配置名称'),
        ),
        migrations.AlterUniqueTogether(
            name='config_confd',
            unique_together={('asset_projenv', 'asset_proj', 'asset_projapp', 'asset_platform', 'confd_name', 'confd_ns')},
        ),
        migrations.AlterUniqueTogether(
            name='confd_detail',
            unique_together={('confd_name', 'confd_ns', 'confd_key')},
        ),
    ]
