# Generated by Django 2.0.5 on 2019-12-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_confd',
            name='asset_platform',
        ),
        migrations.RemoveField(
            model_name='project_confd',
            name='asset_proj',
        ),
        migrations.RemoveField(
            model_name='project_confd',
            name='asset_projapp',
        ),
        migrations.RemoveField(
            model_name='project_confd',
            name='asset_projenv',
        ),
        migrations.DeleteModel(
            name='Project_Confd',
        ),
    ]
