# Generated by Django 2.0.5 on 2019-12-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_auto_20191205_1556'),
        ('confd', '0002_auto_20191219_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Confd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confd_name', models.CharField(max_length=40, verbose_name='配置名称')),
                ('confd_ns', models.CharField(max_length=40, verbose_name='命名空间')),
                ('confd_memo', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('asset_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confd_platform', to='assets.PlatformName', verbose_name='平台')),
                ('asset_proj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.ProjectName', verbose_name='项目')),
                ('asset_projapp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.ProjectApp', verbose_name='应用')),
                ('asset_projenv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.ProjectEnv', verbose_name='环境')),
            ],
            options={
                'verbose_name': '配置表',
                'verbose_name_plural': '配置表',
                'db_table': 'ops_config_confd',
                'permissions': (('confd_projs', '读取confd_projs列表权限'),),
            },
        ),
    ]
