# Generated by Django 2.0.5 on 2019-12-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191205_1556'),
        ('confd', '0003_config_confd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config_confd',
            unique_together={('asset_projenv', 'asset_proj', 'asset_projapp', 'asset_platform', 'confd_name', 'confd_ns')},
        ),
    ]
