# Generated by Django 2.0.5 on 2019-12-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0004_auto_20191219_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confd_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confd_key', models.CharField(max_length=40, unique=True, verbose_name='子项目路径')),
                ('confd_value', models.CharField(max_length=40, verbose_name='程序目录')),
                ('confd_status', models.IntegerField(choices=[(0, 'UP'), (1, 'Down')], default=0, verbose_name='key是否可用')),
                ('confd_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confd.Config_Confd', verbose_name='配置名称')),
            ],
            options={
                'verbose_name': '配置明细',
                'verbose_name_plural': '配置明细',
                'db_table': 'ops_confd_detail',
                'permissions': (('confd_detail', '读取confd_detail列表权限'),),
            },
        ),
    ]
