# Generated by Django 2.0.5 on 2019-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0005_confd_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='confd_detail',
            name='confd_memo',
            field=models.CharField(default=1, max_length=40, verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_key',
            field=models.CharField(max_length=40, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_value',
            field=models.CharField(max_length=40, verbose_name='值'),
        ),
    ]
