# Generated by Django 2.0.5 on 2019-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0006_auto_20191220_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_memo',
            field=models.CharField(blank=True, max_length=40, verbose_name='备注'),
        ),
    ]
