# Generated by Django 2.0.5 on 2019-12-21 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0007_auto_20191220_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='confd_detail',
            name='confd_deploy_status',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='confd_detail',
            name='confd_modified_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confd_detail',
            name='confd_modified_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='最后修改用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confd_detail',
            name='confd_ns',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='命名空间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_status',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='key状态'),
        ),
        migrations.AlterUniqueTogether(
            name='confd_detail',
            unique_together={('confd_name', 'confd_ns', 'confd_key')},
        ),
    ]
