# Generated by Django 2.0.5 on 2019-12-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0008_auto_20191221_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_deploy_status',
            field=models.IntegerField(choices=[(0, '已发布|正常'), (1, '未发布|新'), (2, '无|改'), (3, '无|删')], default=1, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_status',
            field=models.IntegerField(choices=[(0, '已发布|正常'), (1, '未发布|新'), (2, '无|改'), (3, '无|删')], default=1, verbose_name='key状态'),
        ),
    ]
