# Generated by Django 2.0.5 on 2019-12-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0009_auto_20191221_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confd_detail',
            name='confd_modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
