# Generated by Django 2.0.12 on 2020-01-09 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_group_name', models.CharField(max_length=32, unique=True, verbose_name='主机组名称')),
                ('ans_group_vars', models.TextField(blank=True, null=True, verbose_name='主机组变量')),
                ('ans_group_memo', models.TextField(blank=True, null=True, verbose_name='主机组描述')),
                ('ans_group_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('ans_group_hosts', models.ManyToManyField(to='assets.ServerAssets', verbose_name='组内主机')),
            ],
            options={
                'verbose_name': 'Ansible动态主机表',
                'verbose_name_plural': 'Ansible动态主机表',
                'db_table': 'ops_ansible_inventory',
            },
        ),
        migrations.CreateModel(
            name='AnsibleModuleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_remote_ip', models.GenericIPAddressField(verbose_name='操作用户IP')),
                ('ans_module', models.CharField(max_length=100, verbose_name='模块名称')),
                ('ans_args', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='模块参数')),
                ('ans_server', models.TextField(verbose_name='服务器')),
                ('ans_result', models.TextField(verbose_name='执行结果')),
                ('ans_datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('ans_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': 'Ansible模块执行记录表',
                'verbose_name_plural': 'Ansible模块执行记录表',
                'db_table': 'ops_ansible_module_log',
            },
        ),
        migrations.CreateModel(
            name='AnsiblePlaybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=100, unique=True, verbose_name='剧本名称')),
                ('playbook_file', models.FileField(upload_to='playbook/%Y/%m/%d/')),
                ('playbook_content', models.TextField(verbose_name='剧本内容')),
                ('playbook_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('playbook_desc', models.TextField(blank=True, null=True, verbose_name='剧本描述')),
                ('playbook_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人员')),
            ],
            options={
                'verbose_name': 'Ansible剧本信息表',
                'verbose_name_plural': 'Ansible剧本信息表',
                'db_table': 'ops_ansible_playbook',
            },
        ),
        migrations.CreateModel(
            name='AnsiblePlaybookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_remote_ip', models.GenericIPAddressField(verbose_name='操作用户IP')),
                ('playbook_name', models.CharField(max_length=100, verbose_name='剧本名称')),
                ('playbook_result', models.TextField(verbose_name='执行结果')),
                ('playbook_datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('playbook_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': 'Playbook执行记录表',
                'verbose_name_plural': 'Playbook执行记录表',
                'db_table': 'ops_ansible_playbook_log',
            },
        ),
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='role名称')),
                ('role_file', models.FileField(upload_to='roles/')),
                ('role_time', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('role_desc', models.TextField(blank=True, null=True, verbose_name='role描述')),
                ('role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人员')),
            ],
            options={
                'verbose_name': 'AnsibleRole信息表',
                'verbose_name_plural': 'AnsibleRole信息表',
                'db_table': 'ops_ansible_role',
            },
        ),
    ]
