# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_auto_20191121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblerole',
            name='role_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人员'),
        ),
        migrations.AddField(
            model_name='ansibleplaybooklog',
            name='playbook_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='playbook_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加人员'),
        ),
        migrations.AddField(
            model_name='ansiblemodulelog',
            name='ans_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='ansibleinventory',
            name='ans_group_hosts',
            field=models.ManyToManyField(to='assets.ServerAssets', verbose_name='组内主机'),
        ),
    ]
