# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(choices=[('deploy', '部署'), ('rollback', '回滚')], default=0, max_length=10, verbose_name='操作类型')),
                ('branch_tag', models.CharField(default='master', max_length=16, verbose_name='分支或标签名称')),
                ('release_name', models.CharField(max_length=100, verbose_name='部署版本')),
                ('release_desc', models.CharField(max_length=100, verbose_name='版本说明')),
                ('result', models.TextField(verbose_name='部署过程')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '部署记录表',
                'verbose_name_plural': '部署记录表',
                'db_table': 'ops_deploy_log',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('project_env', models.CharField(choices=[('test', '测试环境'), ('fz', '仿真环境'), ('prod', '生产环境')], default='test', max_length=4, verbose_name='项目环境')),
                ('project_web', models.CharField(blank=True, default='', max_length=64, verbose_name='项目网址')),
                ('project_org', models.TextField(blank=True, default='', verbose_name='项目架构JSON数据')),
                ('project_memo', models.TextField(blank=True, default='', verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'ops_project',
                'permissions': (('view_project', '读取项目列表权限'), ('deploy_project', '代码发布权限')),
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(choices=[('svn', 'svn'), ('git', 'git')], max_length=3, verbose_name='仓库类型')),
                ('repo_user', models.CharField(blank=True, default='', max_length=10, verbose_name='仓库用户名')),
                ('repo_password', models.CharField(blank=True, default='', max_length=16, verbose_name='仓库密码')),
                ('repo_url', models.CharField(max_length=100, unique=True, verbose_name='项目仓库路径')),
                ('repo_model', models.CharField(choices=[('branch', 'branch'), ('tag', 'tag'), ('trunk', 'trunk')], default='branch', max_length=10, verbose_name='版本控制类型')),
                ('src_dir', models.CharField(max_length=100, verbose_name='代码检出目录')),
                ('exclude', models.TextField(blank=True, default='', verbose_name='排除文件')),
                ('run_user', models.CharField(default='root', max_length=10, verbose_name='运行服务用户')),
                ('deploy_webroot', models.CharField(max_length=100, verbose_name='目标机器webroot')),
                ('deploy_releases', models.CharField(max_length=100, verbose_name='目标机器版本库地址')),
                ('releases_num', models.PositiveSmallIntegerField(default=20, verbose_name='版本保留个数')),
                ('prev_deploy', models.TextField(blank=True, default='', verbose_name='代码检出前操作')),
                ('post_deploy', models.TextField(blank=True, default='', verbose_name='代码检出后操作')),
                ('prev_release', models.TextField(blank=True, default='', verbose_name='切换版本前操作')),
                ('post_release', models.TextField(blank=True, default='', verbose_name='切换版本后操作')),
                ('versions', models.TextField(blank=True, default='', verbose_name='存储部署过的版本')),
                ('wx_notice', models.BooleanField(default=False, verbose_name='是否开启微信通知')),
                ('to_mail', models.TextField(blank=True, default='', verbose_name='收件人邮箱')),
                ('cc_mail', models.TextField(blank=True, default='', verbose_name='抄送人邮箱')),
                ('deploy_server', models.ManyToManyField(to='assets.ServerAssets', verbose_name='目标部署机器')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projs.Project')),
            ],
            options={
                'verbose_name': '项目配置表',
                'verbose_name_plural': '项目配置表',
                'db_table': 'ops_project_config',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='数据库、中间件等', max_length=32, verbose_name='服务名称')),
                ('service_memo', models.TextField(blank=True, default='', verbose_name='服务描述')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ProjectName')),
                ('service_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets', verbose_name='提供服务的机器')),
            ],
            options={
                'verbose_name': '服务类型表',
                'verbose_name_plural': '服务类型表',
                'db_table': 'ops_service',
            },
        ),
    ]
