# Generated by Django 2.0.5 on 2019-11-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proj_admin', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_member',
            field=models.ManyToManyField(blank=True, related_name='proj_member', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddField(
            model_name='deploylog',
            name='deploy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deploylog',
            name='project_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projs.ProjectConfig'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('service_name', 'service_asset')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_env', 'project_name')},
        ),
    ]
