# Generated by Django 2.0.5 on 2019-11-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0002_auto_20191121_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='cc_mail',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='deploy_server',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='to_mail',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='wx_notice',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='project_role',
            field=models.CharField(default=1, max_length=20, verbose_name='项目角色'),
            preserve_default=False,
        ),
    ]
