# Generated by Django 2.0.5 on 2019-11-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0003_auto_20191125_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfig',
            name='project_role',
            field=models.CharField(max_length=20, verbose_name='项目角色名称'),
        ),
    ]
