# Generated by Django 2.0.5 on 2019-11-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0004_auto_20191125_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Config_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='项目名称')),
                ('proj_env', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='项目环境')),
                ('proj_audit_group', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='项目授权组')),
                ('proj_uuid', models.CharField(max_length=50, verbose_name='唯一id')),
                ('proj_status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='是否可用')),
                ('proj_memo', models.CharField(max_length=20, verbose_name='备注')),
                ('wx_notice', models.BooleanField(default=False, verbose_name='是否开启微信通知')),
                ('to_mail', models.TextField(blank=True, default='', verbose_name='收件人邮箱')),
                ('cc_mail', models.TextField(blank=True, default='', verbose_name='抄送人邮箱')),
            ],
            options={
                'verbose_name': '配置发布工單表',
                'verbose_name_plural': '配置发布工單表',
                'db_table': 'project_config_ticket',
            },
        ),
        migrations.AlterUniqueTogether(
            name='project_config_ticket',
            unique_together={('proj_name', 'proj_env')},
        ),
    ]
