# Generated by Django 2.0.5 on 2019-11-26 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0005_auto_20191126_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
