# Generated by Django 2.0.5 on 2019-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0006_auto_20191126_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_env',
            field=models.SmallIntegerField(default=1, verbose_name='项目环境'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_memo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_name',
            field=models.SmallIntegerField(default=1, verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_status',
            field=models.SmallIntegerField(default=0, verbose_name='是否可用'),
        ),
    ]
