# Generated by Django 2.0.5 on 2019-11-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0007_auto_20191126_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config_ticket',
            name='mail_notice',
            field=models.BooleanField(default=False, verbose_name='是否开启郵件通知'),
        ),
    ]
