# Generated by Django 2.0.5 on 2019-11-27 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0008_project_config_ticket_mail_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config_ticket',
            name='proj_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projs.ProjectConfig', verbose_name='项目角色'),
            preserve_default=False,
        ),
    ]
