# Generated by Django 2.0.5 on 2019-11-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0010_project_config_ticket_proj_branch_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_config_ticket',
            name='proj_branch_tag',
        ),
        migrations.AlterModelTable(
            name='project_config_ticket',
            table='ops_project_config_ticket',
        ),
    ]
