# Generated by Django 2.0.5 on 2019-11-30 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0011_auto_20191130_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config_ticket',
            name='proj_branch_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='项目分支或Tag'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='project_config_ticket',
            table='project_config_ticket',
        ),
    ]
