# Generated by Django 2.0.5 on 2019-11-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0012_auto_20191130_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_config_ticket',
            name='proj_branch_tag',
        ),
    ]
