# Generated by Django 2.0.5 on 2019-11-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0013_remove_project_config_ticket_proj_branch_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config_ticket',
            name='proj_branch_tag',
            field=models.CharField(default='master', max_length=20, verbose_name='项目分支或Tag'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='project_config_ticket',
            table='ops_project_config_ticket',
        ),
    ]
