# Generated by Django 2.0.5 on 2019-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0014_auto_20191130_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_branch_tag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目分支或Tag'),
        ),
    ]
