# Generated by Django 2.0.5 on 2019-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0016_auto_20191130_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_config_ticket',
            name='proj_app',
            field=models.SmallIntegerField(default=1, verbose_name='应用名称'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project_config_ticket',
            unique_together={('proj_name', 'proj_env', 'proj_app')},
        ),
    ]
