# Generated by Django 2.0.5 on 2019-12-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0017_auto_20191130_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ProjectApp', verbose_name='应用名称'),
        ),
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ProjectEnv', verbose_name='项目环境'),
        ),
        migrations.AlterField(
            model_name='project_config_ticket',
            name='proj_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ProjectName', verbose_name='项目名称'),
        ),
    ]
