# Generated by Django 2.0.5 on 2019-12-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191121_1645'),
        ('projs', '0018_auto_20191202_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Deploy_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.BigIntegerField(verbose_name='发布项目ID')),
                ('ticket_user', models.CharField(max_length=30, verbose_name='工单申请人')),
                ('ticket_commit', models.CharField(max_length=100, verbose_name='commit ID')),
                ('ticket_subject', models.CharField(max_length=200, verbose_name='工单申请主题')),
                ('ticket_content', models.TextField(verbose_name='工单申请内容')),
                ('ticket_audit', models.CharField(max_length=30, verbose_name='部署指派人')),
                ('ticket_status', models.IntegerField(choices=[(0, '已通过'), (1, '已拒绝'), (2, '审核中'), (3, '已部署')], default='审核中', verbose_name='工单状态')),
                ('ticket_level', models.IntegerField(choices=[(0, '非紧急'), (1, '紧急')], default='非紧急', verbose_name='工单紧急程度')),
                ('ticket_cancel', models.TextField(blank=True, null=True, verbose_name='取消原因')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='工单最后修改时间')),
                ('ticket_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_config', to='projs.Project_Config_Ticket', verbose_name='关联工单配置表')),
                ('ticket_platform', models.ManyToManyField(related_name='deploy_platform', to='assets.PlatformName', verbose_name='发布平台')),
            ],
            options={
                'verbose_name': '自定义项目部署工单表',
                'verbose_name_plural': '自定义项目部署工单表',
                'db_table': 'ops_apply_deploy_ticket',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apply_deploy_ticket',
            unique_together={('ticket_no', 'ticket_config', 'ticket_commit')},
        ),
    ]
