# Generated by Django 2.0.5 on 2019-12-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191121_1645'),
        ('projs', '0019_auto_20191202_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply_Deploy_Ticket',
            new_name='Project_Deploy_Ticket',
        ),
        migrations.AlterModelTable(
            name='project_deploy_ticket',
            table='ops_project_deploy_ticket',
        ),
    ]
