# Generated by Django 2.0.5 on 2019-12-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0020_auto_20191202_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_deploy_ticket',
            name='ticket_platform',
            field=models.ManyToManyField(blank=True, null=True, related_name='deploy_platform', to='assets.PlatformName', verbose_name='发布平台'),
        ),
    ]
