# Generated by Django 2.0.5 on 2019-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0021_auto_20191202_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_deploy_ticket',
            name='ticket_platform',
            field=models.ManyToManyField(related_name='deploy_platform', to='assets.PlatformName', verbose_name='发布平台'),
        ),
    ]
