# Generated by Django 2.0.5 on 2019-12-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0023_auto_20191210_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_deploy_record',
            name='deploy_status',
            field=models.IntegerField(choices=[(0, '发布失败'), (1, '发布成功'), (2, '回滚失败'), (3, '回滚成功')], default=0, verbose_name='发布状态'),
        ),
    ]
