# Generated by Django 2.0.5 on 2019-12-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0026_auto_20191212_2104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_deploy_record',
            unique_together={('deploy_ip', 'd_ticket_id')},
        ),
    ]
