# Generated by Django 2.0.5 on 2019-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0027_auto_20191212_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_deploy_record',
            name='deploy_status',
            field=models.IntegerField(choices=[(0, '发布失败'), (1, '连接成功'), (2, '代码同步'), (3, '更改属主'), (4, '部署前任务'), (5, '部署代码'), (9, '部署后任务')], default=0, verbose_name='发布状态'),
        ),
    ]
