# Generated by Django 2.0.5 on 2019-12-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0029_auto_20191213_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_deploy_record',
            name='rollback_status',
            field=models.IntegerField(default=0, verbose_name='回滚状态'),
        ),
    ]
