# Generated by Django 2.0.5 on 2019-12-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191205_1556'),
        ('projs', '0030_project_deploy_record_rollback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_deploy_record',
            name='assets_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_deploy_record', to='assets.Assets', verbose_name='关联工单记录表'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_deploy_record',
            name='d_ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deploy_ticket', to='projs.Project_Deploy_Ticket', verbose_name='关联工单记录表'),
        ),
        migrations.AlterField(
            model_name='project_deploy_ticket',
            name='ticket_status',
            field=models.IntegerField(choices=[(0, '已通过'), (1, '已拒绝'), (2, '审核中'), (3, '已部署'), (4, '已回滚')], default='审核中', verbose_name='工单状态'),
        ),
    ]
