# Generated by Django 2.0.5 on 2019-12-16 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191205_1556'),
        ('projs', '0031_auto_20191216_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_deploy_record',
            name='assets_id',
        ),
        migrations.AddField(
            model_name='project_deploy_record',
            name='assets',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_deploy_record', to='assets.Assets', verbose_name='关联资产记录表'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_deploy_ticket',
            name='ticket_status',
            field=models.IntegerField(choices=[(0, '已通过'), (1, '已拒绝'), (2, '审核中'), (3, '已部署'), (4, '已回滚')], default='2', verbose_name='工单状态'),
        ),
    ]
