# Generated by Django 2.0.5 on 2019-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0032_auto_20191216_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_deploy_record',
            old_name='assets',
            new_name='assets_id',
        ),
        migrations.AlterField(
            model_name='project_deploy_ticket',
            name='ticket_status',
            field=models.IntegerField(choices=[(0, '已通过'), (1, '已拒绝'), (2, '审核中'), (3, '已部署'), (4, '已回滚')], default='审核中', verbose_name='工单状态'),
        ),
    ]
