# Generated by Django 2.0.5 on 2019-12-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0033_auto_20191216_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project_deploy_record',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project_deploy_record',
            name='assets_id',
        ),
        migrations.RemoveField(
            model_name='project_deploy_record',
            name='d_ticket_id',
        ),
        migrations.DeleteModel(
            name='Project_Deploy_Record',
        ),
    ]
