# Generated by Django 2.0.5 on 2019-12-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191205_1556'),
        ('projs', '0034_auto_20191216_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Deploy_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_ip', models.GenericIPAddressField(verbose_name='发布IP=资产ID')),
                ('deploy_status', models.IntegerField(choices=[(0, '发布失败'), (1, '连接成功'), (2, '备份成功'), (3, '代码同步'), (4, '更改属主'), (5, '部署前任务'), (6, '部署代码'), (9, '部署后任务')], default=0, verbose_name='发布状态')),
                ('deploy_times', models.IntegerField(default=0, verbose_name='发布次数')),
                ('rollback_status', models.IntegerField(default=0, verbose_name='回滚状态')),
                ('rollback_times', models.IntegerField(default=0, verbose_name='回滚次数')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_deploy_record', to='assets.Assets', verbose_name='关联资产记录表')),
                ('d_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deploy_ticket', to='projs.Project_Deploy_Ticket', verbose_name='关联工单记录表')),
            ],
            options={
                'verbose_name': '发布记录',
                'verbose_name_plural': '发布记录',
                'db_table': 'ops_project_deploy_record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='project_deploy_record',
            unique_together={('deploy_ip', 'd_ticket_id')},
        ),
    ]
