# Generated by Django 2.0.5 on 2019-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projs', '0035_auto_20191216_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfig',
            name='versions',
            field=models.TextField(blank=True, default='', verbose_name='存储部署过的版本'),
        ),
    ]
