# Generated by Django 2.0.12 on 2020-01-09 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='工单标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='工单需求 json 数据')),
                ('result', models.TextField(blank=True, null=True, verbose_name='工单结果 json 数据')),
                ('auditNum', models.SmallIntegerField(default=0, verbose_name='第几个审核人, 为当前审核人（顺序)')),
                ('execNum', models.SmallIntegerField(default=0, verbose_name='第几个执行人，为当前执行人（顺序）')),
                ('status', models.IntegerField(choices=[(1, '待提交'), (2, '审核中'), (3, '执行人确认中'), (4, '执行人执行中'), (5, '执行人延期执行中'), (6, '执行完成,用户确认中'), (7, '审核驳回,等待用户确认'), (8, '执行驳回,等待用户确认'), (9, '用户确认不通过,等待执行重做'), (10, '完成关闭'), (11, '驳回关闭'), (12, '撤销关闭')], default='2', verbose_name='工单状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='工单最后修改时间')),
                ('auditflow', models.SmallIntegerField(default=0, verbose_name='执行流')),
                ('execflow', models.SmallIntegerField(default=0, verbose_name='审核流')),
                ('operation', models.SmallIntegerField(default=0, verbose_name='操作记录')),
                ('createuser_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='工单创建人')),
            ],
            options={
                'verbose_name': '执行流程表',
                'verbose_name_plural': '执行流程',
                'db_table': 'ops_ticket_ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='审核顺序')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核')], default='0', verbose_name='执行状态')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='工单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '执行流程表',
                'verbose_name_plural': '执行流程',
                'db_table': 'ops_ticket_audit',
            },
        ),
        migrations.CreateModel(
            name='TicketAuditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='执行人（可以配置负数表示自动执行）')),
                ('order', models.SmallIntegerField(verbose_name='执行顺序')),
            ],
            options={
                'verbose_name': '执行流程表',
                'verbose_name_plural': '执行流程',
                'db_table': 'ops_ticket_auditmodel',
            },
        ),
        migrations.CreateModel(
            name='TicketExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='审核顺序')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核')], default='0', verbose_name='执行状态')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='工单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '执行流程表',
                'verbose_name_plural': '执行流程',
                'db_table': 'ops_ticket_exec',
            },
        ),
        migrations.CreateModel(
            name='TicketExecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='执行人（可以配置负数表示自动执行）')),
                ('order', models.SmallIntegerField(verbose_name='执行顺序')),
            ],
            options={
                'verbose_name': '执行流程表',
                'verbose_name_plural': '执行流程',
                'db_table': 'ops_ticket_execmodel',
            },
        ),
        migrations.CreateModel(
            name='TicketOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '提交'), (2, '审核通过'), (3, '审核不通过'), (4, '审核转发'), (5, '确认执行'), (6, '执行确认不通过'), (7, '延期执行'), (8, '执行完成'), (9, '执行转发'), (10, '用户确认不通过'), (11, '关闭'), (12, ' 重走流程'), (13, '重新编辑'), (14, '撤回工单'), (15, '回复')], default='1', verbose_name='操作类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='回复内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='工单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '执行流程表',
                'verbose_name_plural': '执行流程',
                'db_table': 'ops_ticket_operation',
            },
        ),
        migrations.CreateModel(
            name='TictetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='工单类型名称')),
                ('confirm_duration', models.IntegerField(default='30', verbose_name='默认确认时长（分）')),
                ('exec_duration', models.IntegerField(default='30', verbose_name='默认执行时长（分）')),
                ('effective_date', models.IntegerField(default='5', verbose_name='默认有效期（天）')),
                ('type_form', models.CharField(blank=True, max_length=64, null=True, verbose_name='工单类型表单')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单类型创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='工单类型最后修改时间')),
                ('status', models.IntegerField(choices=[(1, '启用'), (2, '禁用'), (3, '删除')], default='1', verbose_name='工单状态')),
                ('createuser_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tt_create', to=settings.AUTH_USER_MODEL, verbose_name='工单类型创建人')),
            ],
            options={
                'verbose_name': '工单类型表',
                'verbose_name_plural': '工单类型表：创建工单执行流程和审核流程及工单响应时间',
                'db_table': 'ops_ticket_type',
                'permissions': (('ticket_type_read', '读取工单类型权限'), ('ticket_type_write', '写入工单类型权限')),
            },
        ),
        migrations.AddField(
            model_name='ticketexecmodel',
            name='tt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_model', to='ticket.TictetType', verbose_name='工单类型表'),
        ),
        migrations.AddField(
            model_name='ticketauditmodel',
            name='tt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_model', to='ticket.TictetType', verbose_name='工单类型表'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.TictetType', verbose_name='工单类型'),
        ),
        migrations.AlterUniqueTogether(
            name='tictettype',
            unique_together={('name', 'type_form')},
        ),
    ]
