# Generated by Django 2.0.5 on 2019-12-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketauditmodel',
            name='tt_id',
        ),
        migrations.RemoveField(
            model_name='ticketexecmodel',
            name='tt_id',
        ),
        migrations.AlterUniqueTogether(
            name='tictettype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tictettype',
            name='audit_model',
        ),
        migrations.RemoveField(
            model_name='tictettype',
            name='createuser_id',
        ),
        migrations.RemoveField(
            model_name='tictettype',
            name='exec_model',
        ),
        migrations.DeleteModel(
            name='TicketAuditModel',
        ),
        migrations.DeleteModel(
            name='TicketExecModel',
        ),
        migrations.DeleteModel(
            name='TictetType',
        ),
    ]
