# Generated by Django 2.0.5 on 2019-12-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_auto_20191226_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='工单标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='工单需求 json 数据')),
                ('result', models.TextField(blank=True, null=True, verbose_name='工单结果 json 数据')),
                ('auditNum', models.SmallIntegerField(default=0, verbose_name='第几个审核人, 为当前审核人（顺序)')),
                ('execNum', models.SmallIntegerField(default=0, verbose_name='第几个执行人，为当前执行人（顺序）')),
                ('status', models.IntegerField(choices=[(1, '待提交'), (2, '审核中'), (3, '执行人确认中'), (4, '执行人执行中'), (5, '执行人延期执行中'), (6, '执行完成,用户确认中'), (7, '审核驳回,等待用户确认'), (8, '执行驳回,等待用户确认'), (9, '用户确认不通过,等待执行重做'), (10, '完成关闭'), (11, '驳回关闭'), (12, '撤销关闭')], default='2', verbose_name='工单状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='工单创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='工单最后修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='审核顺序')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核')], default='0', verbose_name='执行状态')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='工单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
        ),
        migrations.CreateModel(
            name='TicketExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='审核顺序')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核')], default='0', verbose_name='执行状态')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='工单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '提交'), (2, '审核通过'), (3, '审核不通过'), (4, '审核转发'), (5, '确认执行'), (6, '执行确认不通过'), (7, '延期执行'), (8, '执行完成'), (9, '执行转发'), (10, '用户确认不通过'), (11, '关闭'), (12, ' 重走流程'), (13, '重新编辑'), (14, '撤回工单'), (15, '回复')], default='1', verbose_name='操作类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='回复内容')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket', verbose_name='工单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
        ),
        migrations.AlterField(
            model_name='tictettype',
            name='type_form',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='工单类型表单'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='auditflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.TicketAudit', verbose_name='审核流'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='createuser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='工单创建人'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='execflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.TicketExec', verbose_name='执行流'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.TicketOperation', verbose_name='操作记录'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.TictetType', verbose_name='工单类型'),
        ),
    ]
