# Generated by Django 2.0.5 on 2019-12-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20191228_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='auditflow',
            field=models.SmallIntegerField(default=0, verbose_name='执行流'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execflow',
            field=models.SmallIntegerField(default=0, verbose_name='审核流'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='operation',
            field=models.SmallIntegerField(default=0, verbose_name='操作记录'),
        ),
    ]
