# Generated by Django 2.0.5 on 2019-12-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20191228_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '执行流程表', 'verbose_name_plural': '执行流程'},
        ),
        migrations.AlterModelOptions(
            name='ticketaudit',
            options={'verbose_name': '执行流程表', 'verbose_name_plural': '执行流程'},
        ),
        migrations.AlterModelOptions(
            name='ticketexec',
            options={'verbose_name': '执行流程表', 'verbose_name_plural': '执行流程'},
        ),
        migrations.AlterModelOptions(
            name='ticketoperation',
            options={'verbose_name': '执行流程表', 'verbose_name_plural': '执行流程'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ops_ticket_ticket',
        ),
        migrations.AlterModelTable(
            name='ticketaudit',
            table='ops_ticket_audit',
        ),
        migrations.AlterModelTable(
            name='ticketexec',
            table='ops_ticket_exec',
        ),
        migrations.AlterModelTable(
            name='ticketoperation',
            table='ops_ticket_operation',
        ),
    ]
